Update dependency caching.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -17,13 +17,49 @@ on:
         description: 'Location of the Release Log file.'
         required: true
 
-env:
-  vulkanSdkVersion: '1.4.328.1'
-  llvmVersion: '20.1.8'
-
 jobs:
+  # ------------------------------------- Toolchain setup      -------------------------------------
+  setup:
+    name: run-setup
+    runs-on: ${{ matrix.os }}
+    timeout-minutes: 10
+    strategy:
+      fail-fast: true
+      matrix:
+        name: [ windows-latest ]
+        include:
+          - name: windows-latest
+            os: windows-latest
+          #- name: ubuntu-latest
+          #  os: ubuntu-latest
+          
+    env:
+      MESA_3D_VERSION: ${{ vars.MESA_3D_VERSION }}
+      VULKAN_SDK_VERSION: ${{ vars.VULKAN_SDK_VERSION }}
+      CACHE_KEY: windows-dependencies-mesa-${{ vars.MESA_3D_VERSION }}-vulkan-${{ vars.VULKAN_SDK_VERSION }}
+
+    steps:
+      - name: Setup dependency directory
+        run: echo "DEPENDENCY_DIR=$env:RUNNER_TEMP/dep/win" >> $env:GITHUB_ENV
+
+      - name: Lookup dependency cache (no restore use)
+        id: cache
+        uses: actions/cache/restore@v6
+        with:
+          path: ${{ env.DEPENDENCY_DIR }}
+          key: ${{ env.CACHE_KEY }}
+          lookup-only: true
+
+      - name: Ensure cache exists
+        if: steps.cache.outputs.cache-hit != 'true'
+        run: |
+          echo "Cache is missing. Please run 'update_dependencies.yml' workflow first."
+          exit 1
+          
+  # ------------------------------------- Build job            -------------------------------------
   build:
     name: Build ${{ matrix.profile }}
+    needs: [ setup ]
     runs-on: windows-latest
     strategy:
       fail-fast: true
@@ -50,26 +86,32 @@ jobs:
       VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}-rel
       VCPKG_FEATURE_FLAGS: 'manifests'
 
+      MESA_3D_VERSION: ${{ vars.MESA_3D_VERSION }}
+      VULKAN_SDK_VERSION: ${{ vars.VULKAN_SDK_VERSION }}
+      LLVM_VERSION: ${{ vars.LLVM_VERSION }}
+      CACHE_KEY: windows-dependencies-mesa-${{ vars.MESA_3D_VERSION }}-vulkan-${{ vars.VULKAN_SDK_VERSION }}
+
     steps:
-      - name: Setup Vulkan SDK 
-        uses: jakoch/install-vulkan-sdk-action@v1
+      - name: Setup dependency directory
+        run: echo "DEPENDENCY_DIR=$env:RUNNER_TEMP/dep/win" >> $env:GITHUB_ENV
+
+      - name: Restore dependency cache
+        uses: actions/cache/restore@v6
         with:
-          vulkan_version: ${{ env.vulkanSdkVersion }}
-          install_runtime: true
-          cache: true
-          stripdown: false
-       
+          path: ${{ env.DEPENDENCY_DIR }}
+          key: ${{ env.CACHE_KEY }}
+
       - name: Setup build environment
         id: setup-environment
         run: |
-          cp "C:\VulkanSDK\${{ env.vulkanSdkVersion }}\runtime\x64\vulkan-1.dll" "C:\Windows\System32\vulkan-1.dll"
-          cp "C:\VulkanSDK\${{ env.vulkanSdkVersion }}\runtime\x86\vulkan-1.dll" "C:\Windows\SysWOW64\vulkan-1.dll"
+          cp "${{ env.DEPENDENCY_DIR }}/vulkan/${{ env.VULKAN_SDK_VERSION }}\runtime\x64\vulkan-1.dll" "C:\Windows\System32\vulkan-1.dll"
+          cp "${{ env.DEPENDENCY_DIR }}/vulkan/${{ env.VULKAN_SDK_VERSION }}\runtime\x86\vulkan-1.dll" "C:\Windows\SysWOW64\vulkan-1.dll"
           
       - name: Update LLVM
         if: ${{ matrix.compiler == 'clang' }}
         uses: KyleMayes/install-llvm-action@v2.0.9
         with:
-          version: ${{ env.llvmVersion }}
+          version: ${{ env.LLVM_VERSION }}
           
       - name: Checking out sources
         uses: actions/checkout@master
@@ -133,7 +175,7 @@ jobs:
       - name: Download windows-msvc-x86 artifacts...
         uses: actions/download-artifact@v4
         with:
-          name: LiteFX_win_x64_msvc
+          name: LiteFX_win_x86_msvc
           path: ${{ github.workspace }}/../.artifacts/msvc/x86/
           
       - name: Download windows-clang-x64 artifacts...
