Update dependency caching.

diff --git a/.github/workflows/weekly.yml b/.github/workflows/weekly.yml
--- a/.github/workflows/weekly.yml
+++ b/.github/workflows/weekly.yml
@@ -12,13 +12,50 @@ on:
   schedule: 
     - cron: '1 0 * * 1'         # Run every monday night at 00:01 AM (UTC).
     
-env:
-  vulkanSdkVersion: '1.4.328.1'
-  llvmVersion: '20.1.8'
-
 jobs:
+  # ------------------------------------- Toolchain setup      -------------------------------------
+  setup:
+    name: run-setup
+    runs-on: ${{ matrix.os }}
+    timeout-minutes: 10
+    strategy:
+      fail-fast: true
+      matrix:
+        name: [ windows-latest ]
+        include:
+          - name: windows-latest
+            os: windows-latest
+          #- name: ubuntu-latest
+          #  os: ubuntu-latest
+                
+    steps:
+      - name: Setup environment
+        run: echo "Setup environment"
+        env:
+          MESA_3D_VERSION: ${{ vars.MESA_3D_VERSION }}
+          VULKAN_SDK_VERSION: ${{ vars.VULKAN_SDK_VERSION }}
+
+          DEPENDENCY_DIR: ${{ runner.temp }}/dep/win
+          CACHE_KEY: windows-dependencies-mesa-${{ vars.MESA_3D_VERSION }}-vulkan-${{ vars.VULKAN_SDK_VERSION }}
+
+      - name: Lookup dependency cache (no restore use)
+        id: cache
+        uses: actions/cache/restore@v6
+        with:
+          path: ${{ env.DEPENDENCY_DIR }}
+          key: ${{ env.CACHE_KEY }}
+          lookup-only: true
+
+      - name: Ensure cache exists
+        if: steps.cache.outputs.cache-hit != 'true'
+        run: |
+          echo "Cache is missing. Please run 'update_dependencies.yml' workflow first."
+          exit 1
+          
+  # ------------------------------------- Build job            -------------------------------------
   job:
     name: windows-latest-weekly
+    needs: [ setup ]
     runs-on: windows-latest
     strategy:
       fail-fast: false
@@ -40,31 +77,38 @@ jobs:
             triplet: x64-windows
             configuration: windows-clang-x64-release
             architecture: x64
-            
-    env:
-      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}-rel
-      VCPKG_FEATURE_FLAGS: 'manifests'
-      
+                  
     steps:
-      - name: Setup Vulkan SDK 
-        uses: jakoch/install-vulkan-sdk-action@v1
+      - name: Setup environment
+        run: echo "Setup environment"
+        env:
+          VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}-rel
+          VCPKG_FEATURE_FLAGS: 'manifests'
+          
+          MESA_3D_VERSION: ${{ vars.MESA_3D_VERSION }}
+          VULKAN_SDK_VERSION: ${{ vars.VULKAN_SDK_VERSION }}
+          LLVM_VERSION: ${{ vars.LLVM_VERSION }}
+
+          DEPENDENCY_DIR: ${{ runner.temp }}/dep/win
+          CACHE_KEY: windows-dependencies-mesa-${{ vars.MESA_3D_VERSION }}-vulkan-${{ vars.VULKAN_SDK_VERSION }}
+
+      - name: Restore dependency cache
+        uses: actions/cache/restore@v6
         with:
-          vulkan_version: ${{ env.vulkanSdkVersion }}
-          install_runtime: true
-          cache: true
-          stripdown: false
-       
+          path: ${{ env.DEPENDENCY_DIR }}
+          key: ${{ env.CACHE_KEY }}
+
       - name: Setup build environment
         id: setup-environment
         run: |
-          cp "C:\VulkanSDK\${{ env.vulkanSdkVersion }}\runtime\x64\vulkan-1.dll" "C:\Windows\System32\vulkan-1.dll"
-          cp "C:\VulkanSDK\${{ env.vulkanSdkVersion }}\runtime\x86\vulkan-1.dll" "C:\Windows\SysWOW64\vulkan-1.dll"
+          cp "${{ env.DEPENDENCY_DIR }}/vulkan/${{ env.VULKAN_SDK_VERSION }}\runtime\x64\vulkan-1.dll" "C:\Windows\System32\vulkan-1.dll"
+          cp "${{ env.DEPENDENCY_DIR }}/vulkan/${{ env.VULKAN_SDK_VERSION }}\runtime\x86\vulkan-1.dll" "C:\Windows\SysWOW64\vulkan-1.dll"
           
       - name: Update LLVM
         if: ${{ matrix.compiler == 'clang' }}
         uses: KyleMayes/install-llvm-action@v2.0.9
         with:
-          version: ${{ env.llvmVersion }}
+          version: ${{ env.LLVM_VERSION }}
 
       - name: Checking out sources
         uses: actions/checkout@master
